### ISSUE TITLE
"Show More" menu doesn't appear with tabs

### ISSUE THREAD

**Issue by snstarosciak** [maslianok/react-responsive-tabs#1]
Hey there, this plugin is extremely nice and well done :)

The only problem I'm having is that when the number of tabs exceeds the width of the panel container, it does not show the "..." for showing more, it just keeps breaking down into multiple rows. I even tried putting your raw example into my project and it still won't show the "..." Any clue what might be the cause? Here are the relevant versions of the modules being used:

"react": "15.0.1",
"react-dom": "15.0.1",

<img width="1058" alt="tabs" src="https://cloud.githubusercontent.com/assets/5612198/15843885/87c1511a-2ca0-11e6-88cb-29c6bceaabe5.png">

**Comment by maslianok** [comment]
Do you run code locally? Or this bug comes from the live demo?

**Comment by snstarosciak** [comment]
It's when I run it locally :(

**Comment by maslianok** [comment]
What browser do you use?

Отправлено с iPhone

> 7 июня 2016 г., в 13:49, Stevie Starosciak <notifications@github.com> написал(а):
> 
> It's when I run it locally :(
>

**Comment by snstarosciak** [comment]
I'm using Chrome on Mac OSX

**Comment by maslianok** [comment]
Please update to v0.5.3

**Comment by snstarosciak** [comment]
Ah thankyou so much it works perfectly :D

If I may ask...do you know if there's a way inside the component that, when
in responsive mode, none of the tabs are selected, if the page is being
loaded the first time? Like not have the first tab selected by default when
in mobile view? Would something like that be possible?

Thanks again, your plugin is amazing :)
