### ISSUE TITLE
dependencies inconsistence

### ISSUE THREAD

**Issue by petrdamborsky** [maslianok/react-responsive-tabs#10]
When I clone the repo and try to install (at OS X), I am running into [issue](https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/116) with one of the eslint plugins.

There's also an error caused by missing [babel plugin](https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-commonjs).

Cannot install and run example because of this.

**Comment by petrdamborsky** [comment]
I tried to fix these issues in PR #11

**Comment by maslianok** [comment]
Merged
