### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by nealoke** [maslianok/react-responsive-tabs#13]
Hi!

Great effort at making this component however I have a few improvements which would be super additions in my opinion:

**-> Have item as a child like so**
```
<Tabs>
	<Item title='item 1'>
		{/* content goes here */}
	</Item>

	<Item title='item 2'>
		{/* content goes here */}
	</Item>
</Tabs>
```

**-> Fix issue for older browsers**
I see that you are using flex but this is not widely supported and not so good if you have an application which needs to support older browsers. See [caniuse](http://caniuse.com/#search=flex). IE support still required in many cases -_-

**Comment by maslianok** [comment]
Hi @nealoke,
Thanks for your proposal!

1. Yeah, that makes sense. Let me play with it a little bit to see all pros and cons.
2. I think we can use autoprefixer to transform styles during the build process. What versions of IE should we support? IE >=10?

**Comment by nealoke** [comment]
@maslianok 

To me it makes not too much sense to have only text in a tab (because it is in an array or so) :) Would love to put custom components in a tab.

I would go down to 9 or 8 even. (there are more people using these then 10), I know it is a pain.

One more thing that might be nice to have is the ability to only render the selected tab, but on tab switch, don't unmount the component but rather hide it. So in essence you only render the tab's content once. (is this making sense?) :)

**Comment by LeoAref** [comment]
@maslianok Do we have any update on the first point? I could make PR for it

**Comment by maslianok** [comment]
Guys, I'm really sorry for not answering you for a long time.

@LeoAref What benefits do you see in @nealoke's suggestion?
I think you can do the same with our current object-oriented approach. Moreover, now we have `getContent` function, that helps you to render tabs lazily (I'm not sure that this is possible with suggested approach).

**Comment by maslianok** [comment]
Close this for now. Please let me know if you want to continue discussion
