### ISSUE TITLE
Seems like lazy rendering breaks selectedTabKey

### ISSUE THREAD

**Issue by dcworldwide** [maslianok/react-responsive-tabs#14]
I have the following component:

```
 <Tabs selectedTabKey={selectedTabKey} items={tabItems} />
```

Where selectedTabKey = 1 and the tabItems array has 2 elements, with keys 1 and 2. When I render the tabs component, no tabs contents are rendered. I have to click either tab 1 or 2 to trigger rendering of content.

**Comment by maslianok** [comment]
I'll check it today. Sorry for this

**Comment by dcworldwide** [comment]
Ok seems that my Tabs component is rendering twice. On first render, selectedTabKey = -1 and therefore doesn't map to any of the tab keys. So this explains why no content is rendered.

I have an async request that resolves (apollo client) a little later after the initial render. At that point, the Tabs component is re-rendered, with selectedTabKey = 1. Interestingly, the Tabs component doesn't seem to respect selectedTabKey re-render.

**Comment by dcworldwide** [comment]
Retracting. This is my mistake. Sorry if you spent anytime looking at it.
