### ISSUE TITLE
Tab Content not re-rendering on props change

### ISSUE THREAD

**Issue by dcworldwide** [maslianok/react-responsive-tabs#16]
I'm having issues re-rendering a tab's content. Perhaps https://github.com/maslianok/react-responsive-tabs/blob/master/src/components/Tab.js#L8 is blocking my re-rendering from happening. 

Example
----

I have a tab as follows:

```
tabItems.push({
			key: 2,
			title: "Equipment & Maintenance",
			getContent: () => {
				console.log(this.props.dimensions.width)
				return <DataTable
					rowData={rowData}
					width={this.props.dimensions.width}>
					// table content here 
				</DataTable>
			}
		})
```

this.props.dimensions.width tracks the width of the table's parent panel. This width of this panel can be re-sized by the user within my app. After they finish resizing the panel, this.props.dimensions.width will be updated with a new value. I need the table rendered within my tab, to re-render using the new width.

How can we change shouldComponentUpdate to support this scenario? I can prove it is an issue with shouldComponentUpdate, as if I switch between tabs and then switch back to this tab, the table re-renders to the correct width.

**Comment by dcworldwide** [comment]
@maslianok One idea that I had, was if we could override/mutate the ShouldComponentUpdate logic.

I.e. 

```
tabItems.push({
			key: 2,
			title: "Equipment & Maintenance",
			getContent: () => {
				console.log(this.props.dimensions.width)
				return <DataTable
					rowData={rowData}
					width={this.props.dimensions.width}>
					// table content here 
				</DataTable>
			},
			shouldUpdate: () => { some true or false logic}
		})
```

Tab's ShouldComponentUpdate would then use this shouldUpdate function to determine if a re-render is required.

What do you think? I'm sure there are other solutions.

**Comment by dcworldwide** [comment]
@maslianok I think I will submit a PR. To save time, please comment on a proposed design for this. I have little time so want to make sure you will accept PR. Thanks

**Comment by maslianok** [comment]
@dcworldwide 

Hi, it's quite popular problem across many libraries.
For example, I've faced up with a similar problem for react-virtualized. They suggested one solution that may work for us as well.

The main idea is to change tab props when you need this.
Can you try to add `this.props.dimensions.width` as a property of tab?

```javascript
tabItems.push({
  key: 2,
  title: "Equipment & Maintenance",
  width: this.props.dimensions.width,
  getContent: () => {},
})
```

It should force rerendering on each `width` change.

**Comment by dcworldwide** [comment]
Neat idea, will try it out this weekend

**Comment by dcworldwide** [comment]
Ok after some debugging I've realized the below code is working correctly

```
tabItems.push({
			key: tabItems.length,
			title: "Equipment Maintenance",
			getContent: () => <WaSrfEquipmentTable wa={this.props.wa} width={this.props.dimensions.width} />
		})
```

When I adjust the width of the tabs container, the following is called

```
shouldComponentUpdate(nextProps, nextState) {
    return this.props.items !== nextProps.items ||
      nextState.blockWidth !== this.state.blockWidth ||
      nextState.selectedTabKey !== this.state.selectedTabKey;
  }
```

For me, shouldComponentUpdate is returning true. I'm not sure if this.props.items !== nextProps.items is true, but  nextState.blockWidth !== this.state.blockWidth is returning true. 

So when render is called, I'd expect due to the changed props, that the panel would re-render. However if you look at the code of getPanelProps (triggered by result.push(<TabPanel {...this.getPanelProps(panel)} />);) you'll see that there the props of the child passed to getContent do not factor in the logic that would force a re-render of the pure Panel component.  

```
  getPanelProps = ({ key, content, getContent, selected, collapsed, className }) => ({
    selected,
    getContent,
    children: content,
    key: panelPrefix + key,
    id: panelPrefix + key,
    tabId: tabPrefix + key,
    classNames: this.getClassNamesFor('panel', { selected, collapsed, className }),
  });
```
