### ISSUE TITLE
Close individual tabs?

### ISSUE THREAD

**Issue by aethant** [maslianok/react-responsive-tabs#22]
Is there a way to close individual tabs from the UI of the component, similar to closing an individual tab in your browser? The docs don't indicate, but I'm wondering if I'm missing it.

**Comment by maslianok** [comment]
Hi @aethant 

The component doesn't keep tabs in the state. Everything renders from the props. The component itself is stateless. So it's your responsibility to process user events and change the props (items) as you want.

But it's very popular question, so I decided to create an example on this.

Demo: http://maslianok.github.io/react-responsive-tabs/
Source code: https://github.com/maslianok/react-responsive-tabs/blob/master/examples/src/TabsRemoval/index.js#L22-L49

Let me know if you will have any questions...

**Comment by aethant** [comment]
I'll take a look. Thank you!
