### ISSUE TITLE
InkBar gets misplaced

### ISSUE THREAD

**Issue by ErreMalote** [maslianok/react-responsive-tabs#24]
if we use the "showMore" feature and the "InkBar". the tabs inside the showMore don't get higlited properly with the inkbar

**Comment by maslianok** [comment]
Yeah, that's true.
This feature is not so easy to implement and, unfortunately, I don't have too much time to work on this right now. So, it would be nice if you can help with this...

**Comment by maslianok** [comment]
Fixed in v2.0.0
