### ISSUE TITLE
Typescript definition

### ISSUE THREAD

**Issue by mightyvyan** [maslianok/react-responsive-tabs#28]
Can you create the typescript definition file upload the node module pack at @types/react-responsive-tabs?

**Comment by maslianok** [comment]
@mightyvyan Sorry, I'm not sure that I understand your request...

**Comment by ritenv** [comment]
Does not work with TypeScript, `@types/react-responsive-tabs` does not exist.

**Comment by maslianok** [comment]
@ritenv can you help us with this? 

If you don't have time - can you at least post some links on how to create these TS modules.

I'm not sure that I have time to work on it these days, but maybe someone else will invest some time into it...

Thanks in advance!

**Comment by TechStudent10** [comment]
I feel like I'm doing this too much but... any update on getting type definitions for this lib?
