### ISSUE TITLE
npm dependancy issue

### ISSUE THREAD

**Issue by ksngits** [maslianok/react-responsive-tabs#29]
Hi, Could you please make it compatible with latest.

> npm ERR! node v6.9.5
> npm ERR! npm  v3.10.10
> npm ERR! code ETARGET
> 
> npm ERR! notarget No compatible version found: react-responsive-tabs@^1.1.1
> npm ERR! notarget Valid install targets:
> npm ERR! notarget 1.0.1, 0.9.0, 0.8.1, 0.8.0, 0.7.1, 0.7.0, 0.6.2, 0.6.1, 0.5.6,
>  0.5.5, 0.5.4, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.9, 0.4.8, 0.4.7, 0.4.6, 0.4.5, 0.
> 4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.3, 0.3.2, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.2
> , 0.1.1, 0.1.0
> npm ERR! notarget
> npm ERR! notarget This is most likely not a problem with npm itself.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> npm ERR! notarget
> npm ERR! notarget It was specified as a dependency of 'material'
> npm ERR! notarget

Seems linked to earlier issue raised [Release version 1.1.0 to NPM](https://github.com/maslianok/react-responsive-tabs/issues/26)

**Comment by maslianok** [comment]
Sorry for this. Done.
