### ISSUE TITLE
Warning: Tabs has a method called shouldComponentUpdate(). 

### ISSUE THREAD

**Issue by adityatambe** [maslianok/react-responsive-tabs#34]
I encountered this warning while using react-responsive-tabs:

`Warning: Tabs has a method called shouldComponentUpdate(). shouldComponentUpdate should not be used when extending React.PureComponent. Please extend React.Component if shouldComponentUpdate is used.`

I suppose using Component instead of PureComponent will resolve the issue.

**Comment by maslianok** [comment]
Fixed in v1.3.0
