### ISSUE TITLE
close already opened accordion in mobile

### ISSUE THREAD

**Issue by sanathko** [maslianok/react-responsive-tabs#41]
The current implementation shows an accordion in mobile and when an accordion panel is opened, we have to click another accordion item, to close the previously opened item.
I would like to know if there is a way to click on the already opened accordion panel, to close it (kind of a toggle behavior).

**Comment by sanathko** [comment]
I've implemented a solution to this problem in my fork (https://github.com/sanathko/react-responsive-tabs). I can't raise a PR because I don't have the proper access to push a branch to maslianok/react-responsive-tabs.

**Comment by maslianok** [comment]
Hi @sanathko 
I reviewed your fork but I think I have a better solution for this task.

This feature is implemented in v3.0.0

Thanks for the feature request!
