### ISSUE TITLE
HTML rendering in tab contents

### ISSUE THREAD

**Issue by btechgroup** [maslianok/react-responsive-tabs#43]
hi guys,

I am trying to render html inside the tab contents. Can you please help?

Regards,
Owais

**Comment by tlehtimaki** [comment]
@btechgroup would you happen to have an example of the code which is not working?

**Comment by btechgroup** [comment]
> @btechgroup would you happen to have an example of the code which is not working?

thanks @tlehtimaki , I got it working, was using a function to return html contents for tabs and there was error in that function.
