### ISSUE TITLE
allowRemove is rendering "X" underneath tab titles

### ISSUE THREAD

**Issue by siivanti** [maslianok/react-responsive-tabs#47]
I've built a custom remove function but I would prefer to use the native allowRemove function. It is rendering the exit button "X" underneath the tab titles.

render() {
    return (
      <Tabs
        allowRemove={true}
        items={this.getTabs()}
        tabsWrapperClass={"subTabs"}
        onChange={this.props.onSubTabChange}
      />
    );
  }
 getTabs = () => {
    return this.state.subTabs.map((subTab, index) => ({
      title: subTab.name,
      getContent: () => subTab.tabContent,
      /* Optional parameters */
      key: index,
      tabClassName: "tab",
      panelClassName: "panel"
    }));
  };

.subTabs {
  width: 314px;
  margin-right: auto;
  margin-left: auto;
  display: flex;
}

Thank you in advance!

**Comment by maslianok** [comment]
Probably, you don't need any help on this issue now :)

But it's better late than never, right?
Finally, I have time to review and fix all issues for this library. I tried to reproduce your issue, but, unfortunately, everything works for me.

Let me know if you still need any help with the library
