### ISSUE TITLE
Request: extract the Tabs component without the panel in separate package

### ISSUE THREAD

**Issue by spiroski** [maslianok/react-responsive-tabs#48]
Hello,

Do you think it would be possible to extract only the components for the navigation tabs? I like this functionality ( the responsiveness ) but I don't use the content/getContent part because I handle it with react router. 

If it's extracted as separate package, this package can depend on it and use it, but also it could be used without the panels and content.

P.S. If you like this idea, I could help with the extraction.

**Comment by maslianok** [comment]
Sorry for the huge delay with the response. Finally, I have time to review all the issues for this library. 

I definitely like the idea of extracting tabs to a separate component. Probably it's too late to accept your proposal to help with this. But maybe you already did it for your project in the past, so it would be great if you can share the code with everyone!

I'm closing the issue for now. We will reopen it in case of any comments.
