### ISSUE TITLE
Keep tabs mounted on tab change

### ISSUE THREAD

**Issue by chriggi** [maslianok/react-responsive-tabs#51]
Is there a way to keep tabs mounted when changing tabs? Similar to the "unmountOnExit" prop in react-bootstrap (https://react-bootstrap.github.io/components/tabs/).

**Comment by maslianok** [comment]
Currently, react-responsive-tabs doesn't support this.

But it's definitely nice to have feature 👍 
It would be great if someone helps us to implement this!

**Comment by maslianok** [comment]
Added `unmountOnExit` prop. Please update to v4
