### ISSUE TITLE
Programatically trigger tab change

### ISSUE THREAD

**Issue by TravelPaddy** [maslianok/react-responsive-tabs#52]
In  a situation where by I have two tabs on a particular page, I want to be able to reload the page and switch back programmatically to the tab that I was on before.

**Comment by maslianok** [comment]
For all who come here with the same problem: you can keep your tab id in the URL-hash or save to local storage and set `selectedTabKey` prop when initialize the component

Something like this
```
<Tabs
  items={...}
  onChange={/*Save tabId here*/}
  selectedTabKey={/*Set selected tabId*/}
/>
```
