### ISSUE TITLE
An Option To Prevent Tab From Changing

### ISSUE THREAD

**Issue by TravelPaddy** [maslianok/react-responsive-tabs#55]
Is it possible to display a confirm prompt when another tab is clicked before it switches? Like let's say when you have an unsaved work on the page and you would like to prevent tab navigation, so that the user can choose to stay or leave the page. 
Or else how can I disable tab navigation? Such that it remains on one tab and the other tabs are disabled.

**Comment by maslianok** [comment]
in the v4.0.1 we added `beforeChange` callback. You can return `false` in order to prevent a tab change.

Let me know if you need any additional help
