### ISSUE TITLE
Replace js-stylesheet with standard stylesheet

### ISSUE THREAD

**Issue by dmitry** [maslianok/react-responsive-tabs#6]
Is there are any specific reason why `js-stylesheet` is used in this module?
Looks like it's much easier to use standard css file, isn't it?

One of the reasons: at the moment it's impossible to switch-off JSS.

**Comment by maslianok** [comment]
@dmitry It would be awesome if we can get rid of this dependency.
But what do you mean under "standard stylesheet"?

I can see the only one solution here - recommend to import styles in your component, e.g.
```javascript
import Tabs from 'react-responsive-tabs';
import 'node_modules/react-responsive-tabs/src/styles.css';
```

Do you have any other suggestions?

**Comment by dmitry** [comment]
I meant the same thing too. Just suggest or recommend somewhere in the README documentation how to import stylesheets, but remove any linkage to a stylesheet from the javascript code at all.

Personally I'm using this module in the rails environment (with `react-rails` gem), and CSS is imported in the general CSS file, not JS.
