### ISSUE TITLE
Optional parameters

### ISSUE THREAD

**Issue by muhammadzubairmoosani** [maslianok/react-responsive-tabs#67]
Optional parameters are not working, I think I'm doing something wrong, I want to include 
"**transform width: 500**" what do I do?.

`const GobalTabs = ({ array }) => {
  const getTabs = () => {
    return array.map((content, index) => ({
      title: content.title,
      getContent: () => content.component,
      transformWidth: 500,
      key: index,
      tabClassName: "tab",
      panelClassName: "panel",
    }));
  };
  return <Tabs items={getTabs()} />;`

**Comment by nvgopi** [comment]
Did u try.. as a props to Tabs just like below?

<Tabs transformWidth: 500 items={getTabs()} />;

**Comment by maslianok** [comment]
<Tabs transformWidth={500} items={getTabs()} />

**Comment by maslianok** [comment]
```
<Tabs transformWidth={500} items={getTabs()} />
```

should work

**Comment by muhammadzubairmoosani** [comment]
Yes! this logic is working well and the issue is resolved to Thank you! nvgopi
