### ISSUE TITLE
Disabled Tabs

### ISSUE THREAD

**Issue by stefensuhat** [maslianok/react-responsive-tabs#69]
I've tried modified selected tabs using for example

```
const handleChangeTab = (value) => {
        if (value < 1) {
            setActiveKey(value);
            return true;
        }

        if (value > 0 && isUpdate) {
            console.log('enter: ', true);

            setActiveKey(value);
        } else {
            setActiveKey(0);
        }
        return false;
    };
```

but still cannot disabled any selected tab.

is there any method to disabled a tab?

**Comment by stefensuhat** [comment]
my bad. it's not written in docs. but i can just put disabled.

**Comment by stefensuhat** [comment]
After testing it, the cursor is show disabled icon but the tab can be clicked. i think it's a bug

**Comment by maslianok** [comment]
If you want to prevent tab change - use `beforeChange` callback. It receives an object `{ selectedTabKey, nextTabKey }`.

`onChange` callback fires **_after_** the tab changes

**Comment by stefensuhat** [comment]
Thanks it works.
