### ISSUE TITLE
how do i implement add more common tab button  

### ISSUE THREAD

**Issue by kishan-tocca** [maslianok/react-responsive-tabs#74]
```
  <Tabs
            items={getTabs()}// need here one extra tab with name add more which is common button
            allowRemove
            onRemove={removeKeynote}
          />
```
![tabs](https://user-images.githubusercontent.com/66630960/93427974-545b8900-f8dc-11ea-9475-2d3335daa870.png)

**Comment by maslianok** [comment]
you can try to add "Add keynote" tab to the end and write some logic to process clicks on that tab.

react-responsive-tabs doesn't provide that functionality out of the box
