### ISSUE TITLE
Issue with styles

### ISSUE THREAD

**Issue by aZolo77** [maslianok/react-responsive-tabs#83]
Hi!
Everything is working fine except that tabs are only shown as an accordion. I render Tabs in a modal window - maybe it affects somehow?

my code:

```
import React from 'react';
import Tabs from 'react-responsive-tabs';

const trfTabs = [{ id: 0, name: 'Смена тарифа', content: '...' }, { id: 1, name: 'Сравнение тарифов', content: '...' }];

function getTabs() {
  return trfTabs.map(tab => ({
    key: tab.id, // - optional
    tabClassName: 'tab', // - optional
    panelClassName: 'panel', // - optional
    title: tab.name,
    transformWidth: 400,
    getContent: () => tab.content,
  }));
}

const ChangeTariffComponent = () => {

  return (
  <div className="change-tariff-wrapper">
    <Tabs items={getTabs()} />
  </div>
  );
};
```

**Comment by aZolo77** [comment]
When I change modal window width more then 800px - tabs  are rerenderin. But I added transformWidth: 400 and still, they change only on 800px.

**Comment by aZolo77** [comment]
For me it was really not clear, that i should use 'transformWidth' not in 
```
trfTabs.map(tab => ({
      ...
    }))
``` here
but in <Tabs ... /> component
Can you add a comment about this in readme.md file please?

**Comment by maslianok** [comment]
Hey @aZolo77,

Thanks for the suggestions! 

All props described in the API section related to the `Tabs` component. There are no other places to add these props to.

But I added an additional notice

```
All entities listed below should be used as props to the Tabs component.

```

I hope it will make things more clear :)
