### ISSUE TITLE
Child components are being rendered even when not active

### ISSUE THREAD

**Issue by petrdamborsky** [maslianok/react-responsive-tabs#9]
I was testing case with 30 tabs. Each has a non-trivial content (e.g. component with SVG content, connected to Redux store). Manipulation with content of active tab was very slow, because all 30 components are actually live even when they aren't visible. This makes the usage of these tabs for anything but simple text/image somewhat slow. The (original) 'react-tabs' do not have this behavior.

**Comment by maslianok** [comment]
Hi @petrdamborsky,
Thanks for your suggestion!

I totally agree with you. We shouldn't render inactive tabs. I'll work on this feature on the weekend.

**Comment by dcworldwide** [comment]
That would be great @maslianok. I've been looking for an alternative to Material-UI Tabs, simply because MUI doesn't lazily render tabs. With this feature, my team could adopt this library and benefit from your excellent responsive design work. :+1:

**Comment by maslianok** [comment]
Starting from v.0.7.0 you can use `getContent` instead of `content` to render only active tab.

Before:

```javascript
{
  title: 'Title',
  content: 'Content',
}
```

After:

```javascript
{
  title: 'Title',
  getContent: () => 'Content',
}
```

Sorry for such a long answer :(

**Comment by dcworldwide** [comment]
Sweet great work!

**Comment by dcworldwide** [comment]
Hey @maslianok,  If I lazily load components as my tab content, will those components be unmounted when the current tab is switched? I want to know if switch tabs preserves component state. This is important for nested tabs. 

I.e.

2 levels of tabs, a parent and nested.

Parent Tabs = A | B | C where A is selected
Nested Tabs = A1 | A2 | A3

Are the following assertions true?

- When A is rendered, if A1 is the default tab, it will be rendered
- If A2 is selected, it will be lazily rendered. 
- If the user then selects B, then goes back to A to re-visit A1 and A2, as A1 and A2 have already been lazily rendered, they will still have the same component state as before

Thanks

**Comment by maslianok** [comment]
No, the component unmounts from the DOM tree when it becomes inactive. So the state gets lost.
Actually, we can either render all tab panels or render only active panel and remove others :)

I see two options for you to avoid this:
1. Use `content` for stateful panel with nested tabs:

```javascript
{
  title: 'Statefull panel with nested tabs',
  content: 'This panel always present in the DOM',
},
{
  title: 'Stateless panel',
  getContent: () => 'This panel renders only when active',
},
```

2. Keep state in the parent component

```javascript
{
  title: 'Statefull panel with nested tabs',
  getContent: () => <Compnent
    onChangeNestedTab={this.onChangeNestedTab}
    activeTab={this.state.activeTab}
  >,
},
```

**Comment by dcworldwide** [comment]
Actually, the more I think about it, the current design is most correct. +1

I think option 2 makes the most sense for me. It is good design to wrap the component in a stateful container. 

Thanks @maslianok
