### ISSUE TITLE
Hidden tabs and Visible tabs list

### ISSUE THREAD

**Issue by thanmaic** [maslianok/react-responsive-tabs#90]
@maslianok Is there a way where we can find the visible tabs and hidden tabs at any point of time?
I mean to ask can we know the list of tabs that are visible and the list of tabs that are under the 'show more' dropdown? 

And also if a tab is selected from dropdown list can we show the selected tab name instead of '...' ?

**Comment by thanmaic** [comment]
@maslianok any update on this?

**Comment by maslianok** [comment]
> @maslianok Is there a way where we can find the visible tabs and hidden tabs at any point of time?
> I mean to ask can we know the list of tabs that are visible and the list of tabs that are under the 'show more' dropdown?

There is no built-in logic for this. You can use standard HTML/JS features to achieve this. For example, you can count children under `.RRT__showmore` element



> And also if a tab is selected from dropdown list can we show the selected tab name instead of '...' ?

Yes, we have `showMoreLabel` prop. You can change it according to the currently selected tab

**Comment by thanmaic** [comment]
Ok will try to work based on your advice. Thanks
