### ISSUE TITLE
Render all tab content on the page?

### ISSUE THREAD

**Issue by K3vinF** [maslianok/react-responsive-tabs#98]
For SEO purposes I would like to have all tab content available on the page. That way search engines can index the content.
Browsing through the code this doesn't seem possible right now?

Or am I missing an option?
I was expecting 'content' to always get rendered, while getContent would be rendered only when the tab gets visible?

**Comment by maslianok** [comment]
Yes, the library has the `content` prop but it works in a different way:

`content` is a sync prop. You can use it to always render a hidden content, e.g.
```
content: "I'm always rendered in a hidden div"
```

`getContent` is an async prop. Use it whenever you need to delay content rendering, e.g.
```
getContent: () => {
  return "I'm rendered only when tab is visible"
}
```

---
`content` is a deprecated property, so it's not mentioned in the readme, but now I see that it may be useful in some cases. I'll update readme
