### ISSUE TITLE
Debugging code is on npm?

### ISSUE THREAD

**Issue by AdamWills** [maslianok/react-responsive-tabs#99]
I've installed this component via npm and am seeing some strange behaviour that I don't quite understand.

On running this the first time, the debugger kicked in... which was strange. I've opened up the `react-responsive-tabs` folder in `node_moduels` and in `lib/index.js`, there's numerous `console.log` statements and even a `debugger` line.

![Screen Shot 2021-07-07 at 9 38 37 AM](https://user-images.githubusercontent.com/3680753/124769003-1f6e0080-df07-11eb-89bd-296725dbf18d.png)

When viewing the source code here on Github, those lines don't exist.

Did some debugging code accidentally make it on npm?

I thought I was seeing things, so did a `rm -rf node_modules && npm install` again... and sure enough, those items are still there.

**Comment by K3vinF** [comment]
Yes,  I can confirm this. 
I ran into the same issue on the latest version (4.4.1)

**Comment by maslianok** [comment]
Sorry guys, this should be fixed now 🙄

**Comment by K3vinF** [comment]
👍🏻 Great, thanks!
